name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python  # This step is not strictly needed anymore
        uses: actions/setup-python@v5 # Unless you use python for other steps
        with:
          python-version: "3.8"

      - name: Detect and tag new version
        id: check-version
        uses: salsify/action-detect-and-tag-new-version@v2.0.3
        with:
          tag-template: '{VERSION}'
          version-command: |
            bash -o pipefail -c "cat ./assets/config.json | jq -r '.version'"

      - name: Create CHANGELOG.md
        if: steps.check-version.outputs.tag
        run: |
          echo "New tag: ${{ steps.check-version.outputs.tag }}"
